language: python

matrix:
  include:
    - python: 3.8
      env: TOXENV=flake8

    - python: 3.8
      env: TOXENV=py38 DEPLOY=true

    - python: 3.7
      env: TOXENV=py37

    - python: 3.6
      env: TOXENV=py36

    - python: 3.5
      env: TOXENV=py35

    - python: 2.7
      env: TOXENV=py27

install:
  - pip install tox

script:
  - tox

after_success:
  - coveralls

deploy:
  provider: pypi
  user: danmichaelo
  password:
    secure: iRaoF9UNIIzwNR2SP60zL7Ub33lgCTYddk4JkpfNNjz/olZaUEGTbrpttq1wQ9thzwYBgp6PbwspgEdIQWOgDLlT75XowkeLpp7UzRNwKjf7gUVaMJuAYtmhbofaWZFGft3zSbsDEt19z8mqepQXSUUN7dcfH4QVUvishElQT5k=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: mwclient/mwclient
    condition: $DEPLOY = true
